Repository stone-payments/pos-mamba-sdk, pull requests merged in 2018-09, with the labels that each got.

#178 Add rule linebreak
  packages/configs/eslint/index.js
Labels: bug

#201 Ponto de entrada virtual para o build de App
  package.json
  packages/webpack/config.base.js
  packages/webpack/helpers/appEntryPoint.js
  packages/webpack/package.json
Labels: breaking, enhancement

#200 Adicionado documetação do drive Card
  packages/pos/docs/Card.md
Labels: documentation, invalid

#202 Jacksongarcia patch 1
  packages/components/Dialog/README.md
Labels: documentation

#212 Refactor base driver to work with signal listener groups
  packages/pos/drivers/base.js
  packages/pos/drivers/extend.js
Labels: enhancement, internal
